Transfer Buttons to Storybook
eggheadio/egghead-io-styleguide pull request #12
Opened 2017-01-02 20:52 UTC by tayiorbeii

First pass at migrating Buttons to Storybook. 
Also updated `tachyons-egghead` in `package.json` to bring in missing Button styles.

Standard View:
![image](https://cloud.githubusercontent.com/assets/2262858/21596039/8e709aec-d0f2-11e6-8853-f3e69a5808e3.png)

Info View (_NOTE: Scrolling seems disabled?_): 
![image](https://cloud.githubusercontent.com/assets/2262858/21596045/ac828ad6-d0f2-11e6-97ae-cb2231cb1757.png)

![image](https://m.popkey.co/98dc6d/Z0798.gif)

2017-01-02 21:18 UTC, joelhooks commented on src/components/Button/index.js
> +const sizes = ['large', 'small', 'cta']
`cta` as a size is 😢 

It's definitely not a size. It's a name a designer gave a particular style in a comp. If it is special it should probably be its own meta-Button and not included in the core framework IMO.

2017-01-02 21:18 UTC, joelhooks commented on src/components/Button/index.examples.js
> +          <div className='mb2 mh2' key={i}>
this particular wrapper is used over and over. Maybe it is a tiny component? Not for the component framework, but just here in the storybook.

2017-01-02 21:27 UTC, joelhooks requested changes

2017-01-02 21:27 UTC, joelhooks commented on src/components/Button/index.js
> +  href: React.PropTypes.string,
If you drop `React` and just use `PropTypes` your build error will cease. It is occurring because you import `PropTypes` and never use it.

2017-01-02 21:53 UTC, trevordmiller commented on src/components/Button/index.examples.js
> +          <div className='mb2 mh2' key={i}>
I would actually vote for not including extra presentational classes in the storybook examples; that way what you see is what you get. yes it wont look as pretty (components will be flush to the edges of the storybook pane) but that is how they are actually rendered when imported so it is more honest. But if you do want presentational styles like this, the way to do it is with the storybook decorators as documented here: https://getstorybook.io/docs/react-storybook/basics/writing-stories

2017-01-02 22:02 UTC, trevordmiller requested changes
Two changes requested. Both would be resolved by following the same setup as the other components already in the style guide ;)

2017-01-02 22:02 UTC, trevordmiller commented on src/components/Button/index.examples.js
> +const dispStyles = 'flex flex-row content-center justify-center flex-wrap items-center vh-100 bg-navy'
See my other comment about display styles

2017-01-02 22:02 UTC, trevordmiller commented on src/components/Button/index.examples.js
> +      {standardButtonExamples.map((btn, i) => {
This mapping can be replaced with the `.addWithPropsCombinations` plugin as used in the other components; a few examples:
- https://github.com/eggheadio/egghead-io-styleguide/blob/master/src/components/Icon/index.examples.js#L12-L15
- https://github.com/eggheadio/egghead-io-styleguide/blob/master/src/components/Heading/index.examples.js#L14-L17

I would recommend in each `index.examples.js` file just including one base "default" `.addWithInfo` and if the component has variations, also include the `.addWithPropsCombinations` as has been done in the other components ^. This auto renders all possibilities of prop input and creates a prop table for documentation automatically. Make sense?

2017-01-02 22:02 UTC, trevordmiller commented on src/components/Button/index.examples.js
> +          <div className='mb2 mh2' key={i}>
I would actually vote for not including extra presentational classes in the storybook examples; that way what you see is what you get. It wont look as pretty (components will be flush to the edges of the storybook pane) but that is how they are actually rendered when imported so it is more honest and free from side effects if composed together into layout component examples. See how the other `index.examples.js` were done and copy that.

Also, fyi, if you did want presentational stuff, the "blessed" way to do it is with the storybook decorators as documented here https://getstorybook.io/docs/react-storybook/basics/writing-stories

2017-01-02 23:00 UTC, tayiorbeii commented on src/components/Button/index.js
> +const sizes = ['large', 'small', 'cta']
renamed to XL

2017-01-02 23:07 UTC, tayiorbeii commented on src/components/Button/index.js
> +  href: React.PropTypes.string,
D'oh! Obvious mistake is obvious.

2017-01-02 23:41 UTC, joelhooks approved these changes

2017-01-02 23:43 UTC, joelhooks commented on src/components/Button/index.js
> +  xl: 'lh-solid ph4 pv4 eh-xl'
if I was being pedantic I'd say `extra-large` since we aren't abbreviating the others. ;)

2017-01-03 20:47 UTC, tayiorbeii commented
@trevordmiller After lots of playing with the techniques you suggested, I think I found a nice medium😎

2017-01-03 20:50 UTC, trevordmiller approved these changes

2017-01-03 21:07 UTC, merged