Add Input and Tooltip
eggheadio/egghead-io-styleguide pull request #18
Opened 2017-01-05 23:13 UTC by tayiorbeii

* Add `<Input />` component
* Add `<Tooltip />` and example `<PasswordTooltip />` components

![image](https://cloud.githubusercontent.com/assets/2262858/21701255/d736ba88-d361-11e6-938f-170896e084eb.png)

![image](http://i.bittwiddlers.org/Lre.gif)

2017-01-05 23:46 UTC, trevordmiller commented on package.json
> +    "tachyons-egghead": "eggheadio/tachyons-egghead#textfield",
What's with the weird version bump?

2017-01-05 23:47 UTC, tayiorbeii commented on package.json
> +    "tachyons-egghead": "eggheadio/tachyons-egghead#textfield",
@trevordmiller I opened a PR to officially bump `tachyons-egghead` to 1.1.6... I aimed `package.json` directly to the branch so I could test both at the same time and then forgot to put it back at first (though I thought I re-pushed here)

2017-01-05 23:48 UTC, tayiorbeii commented on package.json
> +    "tachyons-egghead": "eggheadio/tachyons-egghead#textfield",
@trevordmiller I did `git push origin` instead of `git push upstream`... I should probably just remove `origin`!

2017-01-05 23:50 UTC, trevordmiller requested changes

2017-01-05 23:50 UTC, trevordmiller commented on src/components/Tooltip/index.examples.js
> +    />
Looks like this example needs to be updated from Avatar to Tooltip?

2017-01-05 23:50 UTC, trevordmiller commented on src/components/Tooltip/index.js
> +  strength: React.PropTypes.number.isRequired
The strength values could be an array and you could use .oneOf(strengthValues) instead of just number if only those strength values are accepted

2017-01-06 17:06 UTC, tayiorbeii commented on src/components/Tooltip/index.js
> +  strength: React.PropTypes.number.isRequired
Good call!

2017-01-06 17:12 UTC, tayiorbeii commented
@trevordmiller Updated per comments :)

2017-01-06 17:19 UTC, joelhooks commented on src/components/Tooltip/index.js
> + * Password-specific Tooltip
The password strength stuff seems like it should be its own component to me, some sort of HOC decorator, versus all tooltips having the ability to analyze password strength. The fact that this comment exists is a clear indicator of that for me. 

Can you tell us why the password stuff should be in the base tooltip?

2017-01-06 17:29 UTC, tayiorbeii commented on src/components/Tooltip/index.js
> + * Password-specific Tooltip
@joelhooks I wasn't sure if `<PasswordTooltip />` is too specific when compared with the other things in the Styleguide...  I could go either way on this.

2017-01-06 17:34 UTC, joelhooks commented on src/components/Tooltip/index.js
> + * Password-specific Tooltip
@tayiorbeii there is room for variants of components. The issue with specificity would be application specific. I think password validity/strength logic is definitely out of place in our base tooltip.

I'm fairly anti comments in code, so any time I see them it triggers a "why?" :)

2017-01-06 17:43 UTC, trevordmiller commented on src/components/Tooltip/index.js
> + * Password-specific Tooltip
I agree that comments should only be used if there is something really confusing or whatever - but even then I'd put it in the readme over inline.

2017-01-06 21:10 UTC, tayiorbeii commented
@trevordmiller @joelhooks updated, please check again!

2017-01-06 21:56 UTC, trevordmiller approved these changes
Approved but left a comment for how things could be simplified

2017-01-06 21:56 UTC, trevordmiller commented on src/components/Input/index.examples.js
> +storiesOf('Input')
I'm pretty sure you can combine all the `storiesOf('Thing')` anytime `Thing` is the same - this also removes the need to add the same decorator over and over; so for example, lines 10-44 could be reduced to:

```
storiesOf('Input')
  .addDecorator(...)
  .addWithInfo('Empty field', ...)
  .addWithInfo('Field with placeholder', ...)
  .addWithInfo('Disabled field', ...)
  .etc
```

2017-01-06 23:22 UTC, tayiorbeii commented on src/components/Input/index.examples.js
> +storiesOf('Input')
Updated for this

2017-01-06 23:24 UTC, merged